module netdev {
    header <bar_punk\foo.h>;
    rpc alloc_netdev_mqs {
        projection <struct foo> proj {
            unsigned long long a;
            short b;
            rpc alloc_netdev_mqs c;
            projection global_proj [out, bind(callee)]* d;
        }

        signature projection global_proj [alloc(caller)]* (projection proj [bind(callee)]* foo, projection global_proj * bar, string [in]* name);
    }

    projection <union bar> global_proj {
        unsigned long a;
        short b;
        rpc alloc_netdev_mqs c;
        string [bind(callee)]* d;
    }
}
