module netdev {
    header <bar punk\foo.h>;
    rpc alloc_netdev_mqs {
        projection <struct foo> proj {
            unsigned long long a;
            short b;
            char c;
            projection global_proj [bind(callee)]* d;
        }

        signature projection global_proj [alloc(caller)]* ();
    }

    projection <union bar> global_proj {
        unsigned long a;
        short b;
        char c;
        string d;
    }
}
