include <stdlib.idl>

module kernel(channel c) {

    channel net_async = new async(c);
    use net_async;
    {
        projection <struct foo> foo {
        }
        projection <struct bar> bar {
         rpc int (*play)(projection foo  *cricket);
        }
    }
}

