module foo {
	projection < struct net_device > simp_circ {
        projection simp_circ *a;
    }

    projection < struct net_device > circ_a {
        projection circ_b [in] *a;
    }

    projection <union foo_union> unifoo {
        u32 discrim;
        projection circ_a* a;
        projection circ_b* b;
    }

    projection < struct net_device > circ_b {
        projection circ_a *a;
        const signed char* c;
    }

    rpc projection simp_circ* foo(projection unifoo* c, projection circ_a [out]* a, projection circ_b* b) {}
}
