module foo {
	projection < struct net_device > simp_circ {
        projection simp_circ *a;
    }

    projection < struct net_device > circ_a {
        projection circ_b *a;
    }

    projection < struct net_device > circ_b {
        projection circ_a *a;
    }

    rpc projection simp_circ* foo(projection circ_a* a, projection circ_b* b) {}
}
