module netdev {
    header <bar_punk\foo.h>;

    projection <union bar, this> global_proj {
        unsigned long a;
        short b;
        rpc alloc_netdev_mqs c;
        const string [in, alloc] * const [in, out] d;
        array<const projection global_proj [in, alloc] * const [in, bind] * [in], null> e;
    }

    rpc alloc_netdev_mqs {
        projection <struct foo> proj {
            unsigned long long a;
            short b;
            rpc alloc_netdev_mqs c;
            projection global_proj [out, bind(callee)]* d;
        }

        // foo

        signature projection global_proj [out] (
            projection proj [bind(callee)]* foo,
            projection global_proj * bar,
            array<string [in]*, this->foo->a> dyn_array,
            array<string [in]* [in], null> terminated_array,
            array<string [in]*, 10> sized_array
        );
    }
}
