module kernel() {
    {
        projection <struct dev> dev {
	 rpc int (*open)(void * x);
	 rpc int (*close)(void * x); 
        }
	rpc int register_device(projection dev *device);
	rpc int unregister_device(projection dev *device);
    }
}

