module netdev {
    header <bar_punk\foo.h>;

    projection <union bar, this> global_proj {
        unsigned long a;
        short b;
        rpc alloc_netdev_mqs c;
        const string [bind(callee)] * const [in] d;
    }
}
