module foo {
    rpc add_widget {
        projection <struct bar> foobar {

        }

        projection <union bar, this->foo> foobar {
            
        }

        signature void(projection foobar *foo);
    }
}
