module kernel {

rpc_export int  xhci_gen_setup( projection hcd [alloc<{{sizeof(hcd) + sizeof(struct xhci_hcd)}}>(callee)] *hcd) {
        projection < struct usb_hcd > hcd {
                int [out] speed;
                // normal within - Works
                //unsigned long [within<{{hcd}}, {{speed}}>] *hcd_priv;
                // Needed for xhci-hcd - fails to parse
                //casted<unsigned long *, projection xhci_hcd*> [within<{{hcd}}, {{sizeof(struct xhci_hcd)}}>] hcd_priv;
                // Tried this - it fails to parse too
                //casted<unsigned long *, projection xhci_hcd*> [within<{{hcd}}, {{speed}}>] hcd_priv;
                // fails with assertion
                casted<unsigned long  *, projection xhci_hcd [within<{{hcd}}, {{speed}}>]*> hcd_priv;
        }
        projection <struct xhci_hcd> xhci_hcd {
                char sbrn;
        }
}

}
